
if db(db.disciplinas.id > 0).count() == 0:
	db.disciplinas.insert(id=1, code='ADM01134', name='ADMINISTRAÇÃO E FINANÇAS', short_name='ADM E FINANÇAS')
	db.disciplinas.insert(id=2, code='MAT01355', name='ÁLGEBRA LINEAR I - A', short_name='ÁLGEBRA')
	db.disciplinas.insert(id=3, code='INF01202', name='ALGORÍTMOS E PROGRAMAÇÃO - CIC', short_name='ALGORÍTMOS')
	db.disciplinas.insert(id=4, code='INF01108', name='ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES I', short_name='ARQ1')
	db.disciplinas.insert(id=5, code='INF01112', name='ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES II', short_name='ARQ2')
	db.disciplinas.insert(id=6, code='INF01205', name='CAD PARA SISTEMAS DIGITAIS', short_name='CAD')
	db.disciplinas.insert(id=7, code='MAT01353', name='CÁLCULO E GEOMETRIA ANALÍTICA I - A', short_name='CÁLCULO I')
	db.disciplinas.insert(id=8, code='MAT01354', name='CÁLCULO E GEOMETRIA ANALÍTICA II - A', short_name='CÁLCULO II')
	db.disciplinas.insert(id=9, code='MAT01032', name='CÁLCULO NUMÉRICO A', short_name='CÁLCULO NUMÉRICO')
	db.disciplinas.insert(id=10, code='INF05006', name='CATEGORIAS COMPUTACIONAIS N', short_name='CATEGORIAS')
	db.disciplinas.insert(id=11, code='INF01124', name='CLASSIFICAÇÃO E PESQUISA DE DADOS', short_name='CPD')
	db.disciplinas.insert(id=12, code='INF01147', name='COMPILADORES', short_name='COMPILADORES')
	db.disciplinas.insert(id=13, code='INF05515', name='COMPLEXIDADE DE ALGORITMOS - B', short_name='COMPLEXIDADE')
	db.disciplinas.insert(id=14, code='INF01140', name='COMPUTADOR E SOCIEDADE', short_name='COMPUTADOR E SOCIEDADE')
	db.disciplinas.insert(id=15, code='INF01005', name='COMUNICAÇÃO DE DADOS', short_name='COMUNICAÇÃO DE DADOS')
	db.disciplinas.insert(id=16, code='INF01185', name='CONCEPÇÃO DE CIRCUITOS INTEGRADOS I', short_name='CIRCUITOS I')
	db.disciplinas.insert(id=17, code='INF01194', name='CONCEPÇÃO DE CIRCUITOS INTEGRADOS II', short_name='CIRCUITOS II')
	db.disciplinas.insert(id=18, code='ECO02254', name='ECONOMIA A', short_name='ECONOMIA')
	db.disciplinas.insert(id=19, code='INF01032', name='EMPREENDIMENTO EM INFORMÁTICA', short_name='EMPREENDIMENTOS')
	db.disciplinas.insert(id=20, code='INF01127', name='ENGENHARIA DE SOFTWARE N', short_name='ENG SOFT')
	db.disciplinas.insert(id=21, code='INF01001', name='ESPECIFICAÇÃO FORMAL N', short_name='ESPECIFICAÇÃO')
	db.disciplinas.insert(id=22, code='INF01203', name='ESTRUTURAS DE DADOS', short_name='ESTRUTURAS')
	db.disciplinas.insert(id=23, code='INF05008', name='FUNDAMENTOS DE ALGORITMOS', short_name='FUNDAMENTOS')
	db.disciplinas.insert(id=24, code='INF01145', name='FUNDAMENTOS DE BANCO DE DADOS', short_name='FBD')
	db.disciplinas.insert(id=25, code='INF01047', name='FUNDAMENTOS DE COMPUTAÇÃO GRÁFICA', short_name='FCG')
	db.disciplinas.insert(id=26, code='INF01046', name='FUNDAMENTOS DE PROCESSAMENTO DE IMAGENS', short_name='FPI')
	db.disciplinas.insert(id=27, code='INF01209', name='FUNDAMENTOS DE TOLERÂNCIA A FALHAS', short_name='TF')
	db.disciplinas.insert(id=28, code='INF01016', name='GERÊNCIA E ADMINISTRAÇÃO DE PROJETOS', short_name='GERÊNCIA DE PROJETOS')
	db.disciplinas.insert(id=29, code='INF01015', name='GERÊNCIA E APLICAÇÕES EM REDES', short_name='GERÊNCIA DE REDES')
	db.disciplinas.insert(id=30, code='INF01048', name='INTELIGÊNCIA ARTIFICIAL', short_name='IA')
	db.disciplinas.insert(id=31, code='INF05004', name='INTELIGÊNCIA ARTIFICIAL AVANÇADA', short_name='IA AVANÇADA')
	db.disciplinas.insert(id=32, code='INF01043', name='INTERAÇÃO HOMEM-COMPUTADOR', short_name='IHC')
	db.disciplinas.insert(id=33, code='INF01107', name='INTRODUÇÃO À ARQUITETURA DE COMPUTADORES', short_name='ARQ0')
	db.disciplinas.insert(id=34, code='INF01022', name='LABORATÓRIO DE SISTEMA DE SOFTWARE', short_name='LABORATÓRIO DE SOFTWARE')
	db.disciplinas.insert(id=35, code='INF05005', name='LINGUAGENS FORMAIS E AUTÔMATOS N', short_name='FORMAIS')
	db.disciplinas.insert(id=36, code='INF05508', name='LÓGICA PARA COMPUTAÇÃO', short_name='LÓGICA')
	db.disciplinas.insert(id=37, code='MAT01375', name='MATEMÁTICA DISCRETA B', short_name='DISCRETA')
	db.disciplinas.insert(id=38, code='INF01121', name='MODELOS DE LINGUAGEM DE PROGRAMAÇÃO', short_name='MLP')
	db.disciplinas.insert(id=39, code='INF01113', name='ORGANIZAÇÃO DE COMPUTADORES B', short_name='ORGB')
	db.disciplinas.insert(id=40, code='INF05010', name='OTIMIZAÇÃO COMBINATÓRIA', short_name='OTIMIZATION')
	db.disciplinas.insert(id=41, code='MAT02219', name='PROBABILIDADE E ESTATÍSTICA', short_name='PROB')
	db.disciplinas.insert(id=42, code='INF01006', name='PROJETO DE BANCO DE DADOS', short_name='PBD')
	db.disciplinas.insert(id=43, code='INF01021', name='PROJETO DE HIPERDOCUMENTOS', short_name='HIPERDOCUMENTOS')
	db.disciplinas.insert(id=44, code='INF01019', name='PROJETO EM COMPUTAÇÃO GRÁFICA', short_name='PCG')
	db.disciplinas.insert(id=45, code='INF0854', name='REDES DE COMPUTADORES N', short_name='REDES')
	db.disciplinas.insert(id=46, code='INF01017', name='REDES NEURAIS E SISTEMAS FUZZY', short_name='SISTEMAS FUZZY')
	db.disciplinas.insert(id=47, code='INF01045', name='SEGURANÇA EM SISTEMAS DE COMPUTAÇÃO', short_name='SEGURANÇA')
	db.disciplinas.insert(id=48, code='INF05516', name='SEMÂNTICA FORMAL N', short_name='SEMÂNTICA')
	db.disciplinas.insert(id=49, code='INF01175', name='SISTEMAS DIGITAIS PARA COMPUTADORES A', short_name='SISTEMAS DIGITAIS')
	db.disciplinas.insert(id=50, code='INF01059', name='SISTEMAS EMBARCADOS', short_name='SISTARMAS EMBARCADOS')
	db.disciplinas.insert(id=51, code='INF01038', name='SISTEMAS ESPECIALISTAS N', short_name='SISTEMAS ESPECIALISTAS')
	db.disciplinas.insert(id=52, code='INF01142', name='SISTEMAS OPERACIONAIS I N', short_name='SISOP I')
	db.disciplinas.insert(id=53, code='INF01151', name='SISTEMAS OPERACIONAIS II N', short_name='SISOP II')
	db.disciplinas.insert(id=54, code='INF01120', name='TÉCNICAS DE CONSTRUÇÃO DE PROGRAMAS', short_name='TCP')
	db.disciplinas.insert(id=55, code='INF01118', name='TÉCNICAS DIGITAIS PARA COMPUTAÇÃO', short_name='TD')
	db.disciplinas.insert(id=56, code='INF05501', name='TEORIA DA COMPUTAÇÃO N', short_name='TEORIA')
	db.disciplinas.insert(id=57, code='INF05512', name='TEORIA DOS GRAFOS E ANÁLISE COMBINATÓRIA', short_name='GRAFOS')
	db.disciplinas.insert(id=58, code='INF01182', name='TÓPICOS ESPECIAIS EM COMPUTAÇÃO II', short_name='TÓPICOS ESP. II')
	db.disciplinas.insert(id=59, code='INF05013', name='TÓPICOS ESPECIAIS EM COMPUTAÇÃO XV', short_name='TÓPICOS ESP. XV')
	db.disciplinas.insert(id=60, code='INF01062', name='TÓPICOS ESPECIAIS EM COMPUTAÇÃO XVI', short_name='TÓPICOS ESP. XVI')
	db.disciplinas.insert(id=61, code='INF05016', name='TÓPICOS ESPECIAIS EM COMPUTAÇÃO XXI', short_name='TÓPICOS ESP. XXI')
	db.disciplinas.insert(id=62, code='INF01023', name='ARQUITETURA E DESEMPENHO DE BANCO DE DADOS', short_name='ARQ E DESEMP BD')
	db.disciplinas.insert(id=63, code='INF01009', name='COMPUTAÇÃO GRÁFICA', short_name='CG')
	db.disciplinas.insert(id=64, code='INF01210', name='INTRODUÇÃO À INFORMÁTICA', short_name='INTROD. INF.')
	db.disciplinas.insert(id=65, code='INF01240', name='INTRODUÇÃO À PROGRAMAÇÃO', short_name='INTROD. PROG.')
	db.disciplinas.insert(id=66, code='INF01034', name='ROBÓTICA II', short_name='ROBÓTICA')
	db.disciplinas.insert(id=67, code='INF01037', name='COMPUTAÇÃO EVOLUTIVA', short_name='COMP. EVOL.')
	db.disciplinas.insert(id=68, code='INF01191', name='ARQUITETURAS AVANÇADAS DE COMPUTADORES', short_name='ARQ. AVANÇADAS')
	db.disciplinas.insert(id=69, code='INF01049', name='INTRODUÇÃO À PESQUISA EM INFORMÁTICA', short_name='INTROD PESQ INF')
	db.disciplinas.insert(id=70, code='INF01014', name='SISTEMAS DE BANCO DE DADOS DISTRIBUÍDOS', short_name='SIST. BD. DISTRIB.')
	db.disciplinas.insert(id=71, code='INF01056', name='DESAFIOS DE PROGRAMAÇÃO', short_name='DESAFIOS')
	db.disciplinas.insert(id=72, code='INF01002', name='PROTOCOLOS DE COMUNICAÇÃO', short_name='PROTOCOLOS')
	db.disciplinas.insert(id=73, code='INF01003', name='ENGENHARIA DE SOFTWARE II', short_name='ENG. SOFT. II')
	db.disciplinas.insert(id=74, code='INF01146', name='AVALIAÇÃO DE DESEMPENHO', short_name='AVAL. DESEMP.')
