
if db(db.profs_discs.id > 0).count() == 0:
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('asc@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('asc@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01112'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('asc@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('asc@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01151'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('avillavicencio@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05005'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bazzan@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05004'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bazzan@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05005'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bazzan@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bazzan@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01019'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('andreis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('andreis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('andreis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01175'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('andreis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carla@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01047'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carla@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01043'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carla@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01019'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carla@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01009'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('heuser@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01145'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('heuser@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01006'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('calisboa@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('calisboa@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cirano@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01145'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cirano@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01023'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('geyer@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01151'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('geyer@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('crjung@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('MAT01353'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('crjung@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('MAT01032'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cora@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cora@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01006'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cora@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01210'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('daltro@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01203'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('daltro@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05516'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('barone@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01034'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('barone@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01037'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('barone@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01140'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('prestes@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05512'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('prestes@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05515'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fglima@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fglima@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01112'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fglima@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01175'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fernando@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01191'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fernando@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fernando@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01210'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('fernando@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('flavio@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('flavio@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('flavio@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('brodbeck@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01032'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('ingrid@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01209'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('ingrid@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('ingrid@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('ingrid@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('ingrid@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01049'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('jacobs@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01046'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('jacobs@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01019'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('palazzo@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01124'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('palazzo@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01014'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('valdeni@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01021'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('netto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('netto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('netto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01112'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('comba@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01056'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('comba@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01047'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('comba@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01019'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('comba@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01147'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('wives@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01121'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('wives@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('leila@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('leila@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05006'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('leila@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05516'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('leila@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05515'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('granville@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01016'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('granville@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01002'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('granville@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('granville@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nedel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01047'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nedel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01203'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nedel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01210'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nedel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01240'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nedel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01240'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('buriol@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05515'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('buriol@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05010'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('buriol@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('paschoal@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01015'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('paschoal@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01002'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('paschoal@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('lmduarte@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('lmduarte@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carro@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('carro@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('alvares@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01048'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('alvares@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05004'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('lamb@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bercht@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bercht@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01121'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bercht@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01121'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('oliveira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01124'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('oliveira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01046'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('oliveira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01009'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('marabel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('marabel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01038'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('marabel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01048'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mpimenta@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01022'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mpimenta@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01120'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mpimenta@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01043'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mpimenta@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01003'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('johann@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01142'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('johann@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('johann@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01120'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mrpritt@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mrpritt@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05010'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('mrpritt@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05516'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('souto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01210'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('souto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01240'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('souto@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01203'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('marinho@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01142'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('newton@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01140'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('newton@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01032'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nicolas@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01147'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('nicolas@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01142'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('blauth@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05006'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('blauth@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05005'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('blauth@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05501'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('engel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01048'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('engel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01017'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('engel@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05004'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('navaux@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bordini@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01142'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bordini@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05005'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bordini@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05008'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bordini@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05516'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('weber@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('weber@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('weber@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01112'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('weber@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01045'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('galante@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01203'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('rpribas@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01185'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('rpribas@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01194'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('rpribas@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('reis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01185'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('reis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01194'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('reis@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cabral@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('MAT01355'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('rdasilva@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05512'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('rdasilva@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05515'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bampi@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01175'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bampi@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01118'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bampi@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01113'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bampi@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01191'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('bampi@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01185'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('zirbes@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01127'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('zirbes@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01016'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('zirbes@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01003'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cechin@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cechin@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cechin@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01142'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cechin@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('cechin@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01146'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('taisy@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01209'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('taisy@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01112'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('taisy@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01108'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('diverio@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05501'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('roesler@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('viviane@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01203'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('viviane@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01202'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('afmoreira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05516'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('afmoreira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('afmoreira@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF05005'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('erika@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01121'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('erika@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01107'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('erika@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01043'))
	db.profs_discs.insert(
		professor_id=get_prof_id_from_email('marinho@inf.ufrgs.br'),
		disciplina_id=get_disc_id_from_code('INF01154'))
