
if db(db.professores.id > 0).count() == 0:
	db.professores.insert(id=1, email='flavio@inf.ufrgs.br', short_name='Flávio', full_name='Flávio Rech Wagner', site='http://www.inf.ufrgs.br/~flavio')
	db.professores.insert(id=2, email='lamb@inf.ufrgs.br', short_name='Lamb', full_name='Luís da Cunha Lamb', site='http://www.inf.ufrgs.br/~lamb')
	db.professores.insert(id=3, email='heuser@inf.ufrgs.br', short_name='Heuser', full_name='Carlos Alberto Heuser', site='http://www.inf.ufrgs.br/~heuser')
	db.professores.insert(id=4, email='daltro@inf.ufrgs.br', short_name='Daltro', full_name='Daltro José Nunes')
	db.professores.insert(id=5, email='palazzo@inf.ufrgs.br', short_name='Palazzo', full_name='José Palazzo Moreira de Oliveira', site='http://www.inf.ufrgs.br/~palazzo')
	db.professores.insert(id=6, email='navaux@inf.ufrgs.br', short_name='Navaux', full_name='Philippe Olivier Alexandre Navaux', site='http://www.inf.ufrgs.br/~navaux')
	db.professores.insert(id=7, email='reis@inf.ufrgs.br', short_name='Reis', full_name='Ricardo Augusto da Luz Reis')
	db.professores.insert(id=8, email='asc@inf.ufrgs.br', short_name='Carissimi', full_name='Alexandre da Silva Carissimi', site='http://www.inf.ufrgs.br/~asc', picture='professores.picture.9162850d94a79ce7.6173632e6a7067.jpg')
	db.professores.insert(id=9, email='bazzan@inf.ufrgs.br', short_name='Bazzan', full_name='Ana Lucia Cetertich Bazzan', site='http://www.inf.ufrgs.br/~bazzan')
	db.professores.insert(id=10, email='carla@inf.ufrgs.br', short_name='Carla', full_name='Carla Maria Dal Sasso Freitas', site='http://www.inf.ufrgs.br/~carla')
	db.professores.insert(id=11, email='calisboa@inf.ufrgs.br', short_name='Lisboa', full_name='Carlos Arthur Lang Lisboa', site='http://www.inf.ufrgs.br/~calisboa')
	db.professores.insert(id=12, email='cora@inf.ufrgs.br', short_name='Cora', full_name='Cora Helena Francisconi Pinto Ribeiro', site='http://www.inf.ufrgs.br/~cora')
	db.professores.insert(id=13, email='barone@inf.ufrgs.br', short_name='Barone', full_name='Dante Augusto Couto Barone', site='http://www.inf.ufrgs.br/~barone')
	db.professores.insert(id=14, email='ingrid@inf.ufrgs.br', short_name='Ingrid', full_name='Ingrid Eleonora Schreiber Jansch Pôrto', site='http://www.inf.ufrgs.br/~ingrid/')
	db.professores.insert(id=15, email='jacobs@inf.ufrgs.br', short_name='Jacob', full_name='Jacob Scharcanski', site='http://www.inf.ufrgs.br/~jacobs')
	db.professores.insert(id=16, email='netto@inf.ufrgs.br', short_name='Netto', full_name='João Cesar Netto', site='http://www.inf.ufrgs.br/~netto')
	db.professores.insert(id=17, email='valdeni@inf.ufrgs.br', short_name='Valdeni', full_name='José Valdeni de Lima', site='http://www.inf.ufrgs.br/~valdeni/')
	db.professores.insert(id=18, email='leila@inf.ufrgs.br', short_name='Leila', full_name='Leila Ribeiro', site='http://www.inf.ufrgs.br/~leila')
	db.professores.insert(id=19, email='carro@inf.ufrgs.br', short_name='Luigi', full_name='Luigi Carro', site='http://www.inf.ufrgs.br/~carro')
	db.professores.insert(id=20, email='alvares@inf.ufrgs.br', short_name='Luis Otavio', full_name='Luis Otavio Campos Alvares', site='http://www.inf.ufrgs.br/~alvares')
	db.professores.insert(id=21, email='bercht@inf.ufrgs.br', short_name='Magda', full_name='Magda Bercht', site='http://www.inf.ufrgs.br/~bercht')
	db.professores.insert(id=22, email='souto@inf.ufrgs.br', short_name='Cida Souto', full_name='Maria Aparecida Martins Souto', site='http://www.inf.ufrgs.br/~souto')
	db.professores.insert(id=23, email='blauth@inf.ufrgs.br', short_name='Blauth', full_name='Paulo Fernando Blauth Menezes')
	db.professores.insert(id=24, email='engel@inf.ufrgs.br', short_name='Engel', full_name='Paulo Martins Engel', site='http://www.inf.ufrgs.br/~engel')
	db.professores.insert(id=25, email='weber@inf.ufrgs.br', short_name='Weber', full_name='Raul Fernando Weber', site='http://www.inf.ufrgs.br/~weber')
	db.professores.insert(id=26, email='rpribas@inf.ufrgs.br', short_name='Ribas', full_name='Renato Perez Ribas', site='http://www.inf.ufrgs.br/~rpribas')
	db.professores.insert(id=27, email='rosa@inf.ufrgs.br', short_name='Rosa', full_name='Rosa Maria Viccari', site='http://www.inf.ufrgs.br/~rosa')
	db.professores.insert(id=28, email='bampi@inf.ufrgs.br', short_name='Bampi', full_name='Sérgio Bampi', site='http://www.inf.ufrgs.br/gme')
	db.professores.insert(id=29, email='zirbes@inf.ufrgs.br', short_name='Zirbes', full_name='Sérgio Felipe Zirbes', site='http://www.inf.ufrgs.br/~zirbes/')
	db.professores.insert(id=30, email='taisy@inf.ufrgs.br', short_name='Taisy', full_name='Taisy Silva Weber', site='http://www.inf.ufrgs.br/~taisy')
	db.professores.insert(id=31, email='diverio@inf.ufrgs.br', short_name='Tiaraju', full_name='Tiaraju Asmuz Diverio')
	db.professores.insert(id=32, email='avillavicencio@inf.ufrgs.br', short_name='Aline', full_name='Aline Villavicencio', site='http://www.inf.ufrgs.br/~avillavicencio')
	db.professores.insert(id=33, email='afmoreira@inf.ufrgs.br', short_name='Álvaro', full_name='Álvaro Freitas Moreira', site='http://www.inf.ufrgs.br/~afmoreiras')
	db.professores.insert(id=34, email='andreis@inf.ufrgs.br', short_name='André', full_name='André Inácio Reis', site='http://www.inf.ufrgs.br/~andreis')
	db.professores.insert(id=35, email='cirano@inf.ufrgs.br', short_name='Cirano', full_name='Cirano Iochpe')
	db.professores.insert(id=36, email='geyer@inf.ufrgs.br', short_name='Geyer', full_name='Cláudio Fernando Resin Geyer', site='http://www.inf.ufrgs.br/~geyer')
	db.professores.insert(id=37, email='crjung@inf.ufrgs.br', short_name='Jung', full_name='Cláudio Jung', site='http://www.inf.ufrgs.br/~crjung')
	db.professores.insert(id=38, email='prestes@inf.ufrgs.br', short_name='Prestes', full_name='Edson Prestes e Silva Júnior', site='http://www.inf.ufrgs.br/~prestes')
	db.professores.insert(id=39, email='erika@inf.ufrgs.br', short_name='Érika', full_name='Érika Fernandes Cota', site='http://www.inf.ufrgs.br/~erika')
	db.professores.insert(id=40, email='fglima@inf.ufrgs.br', short_name='Fernanda', full_name='Fernanda Gusmão de Lima Kastensmidt', site='http://www.inf.ufrgs.br/~fglima')
	db.professores.insert(id=41, email='fernando@inf.ufrgs.br', short_name='Fernando', full_name='Fernando Rosa do Nascimento', site='http://www.inf.ufrgs.br/~fernando')
	db.professores.insert(id=42, email='vauthier@inf.ufrgs.br', short_name='Helena', full_name='Helena Saint Pastous Vauthier de Souza')
	db.professores.insert(id=43, email='brodbeck@inf.ufrgs.br', short_name='Brodbeck', full_name='Henrique Jorge Brodbeck', site='http://www.inf.ufrgs.br/~brodbeck')
	db.professores.insert(id=44, email='comba@inf.ufrgs.br', short_name='Comba', full_name='João Luiz Dihl Comba', site='http://www.inf.ufrgs.br/~comba')
	db.professores.insert(id=45, email='wives@inf.ufrgs.br', short_name='Leandro', full_name='Leandro Krug Wives', site='http://www.inf.ufrgs.br/~wives')
	db.professores.insert(id=46, email='granville@inf.ufrgs.br', short_name='Lisandro', full_name='Lisandro Zambenedetti Granville', site='http://www.inf.ufrgs.br/~granville')
	db.professores.insert(id=47, email='nedel@inf.ufrgs.br', short_name='Nedel', full_name='Luciana Porcher Nedel', site='http://www.inf.ufrgs.br/~nedel')
	db.professores.insert(id=48, email='buriol@inf.ufrgs.br', short_name='Buriol', full_name='Luciana Salete Buriol', site='http://www.inf.ufrgs.br/~buriol')
	db.professores.insert(id=49, email='paschoal@inf.ufrgs.br', short_name='Paschoal', full_name='Luciano Paschoal Gaspary', site='http://www.inf.ufrgs.br/~paschoal')
	db.professores.insert(id=50, email='lmduarte@inf.ufrgs.br', short_name='Lucio', full_name='Lucio Mauro Duarte', site='http://www.inf.ufrgs.br/~lmduarte')
	db.professores.insert(id=51, email='oliveira@inf.ufrgs.br', short_name='Manuel', full_name='Manuel Menezes de Oliveira Neto', site='http://www.inf.ufrgs.br/~oliveira')
	db.professores.insert(id=52, email='marabel@inf.ufrgs.br', short_name='Mara', full_name='Mara Abel', site='http://www.inf.ufrgs.br/~marabel')
	db.professores.insert(id=53, email='johann@inf.ufrgs.br', short_name='Johann', full_name='Marcelo de Oliveira Johann')
	db.professores.insert(id=54, email='mpimenta@inf.ufrgs.br', short_name='Pimenta', full_name='Marcelo Soares Pimenta', site='http://www.inf.ufrgs.br/~mpimenta')
	db.professores.insert(id=55, email='marcelo.walter@inf.ufrgs.br', short_name='Walter', full_name='Marcelo Walter', site='http://www.inf.ufrgs.br/~mwalter/')
	db.professores.insert(id=56, email='mrpritt@inf.ufrgs.br', short_name='Ritt', full_name='Marcus Rolf Peter Ritt', site='Marcus Rolf Petter Ritt')
	db.professores.insert(id=57, email='marinho@inf.ufrgs.br', short_name='Marinho', full_name='Marinho Pilla Barcellos', site='http://www.inf.ufrgs.br/~marinho')
	db.professores.insert(id=58, email='newton@inf.ufrgs.br', short_name='Newton', full_name='Newton Braga Rosa')
	db.professores.insert(id=59, email='nicolas@inf.ufrgs.br', short_name='Nicolas', full_name='Nicolas Bruno Maillard', site='http://www.inf.ufrgs.br/~nicolas')
	db.professores.insert(id=60, email='r.bordini@inf.ufrgs.br', short_name='Bordini', full_name='Rafael Heitor Bordini', site='http://www.inf.ufrgs.br/~bordini/')
	db.professores.insert(id=61, email='galante@inf.ufrgs.br', short_name='Renata', full_name='Renata de Matos Galante', site='http://www.inf.ufrgs.br/~galante')
	db.professores.insert(id=62, email='binsely@inf.ufrgs.br', short_name='Bins Ely', full_name='Roberto Bins Ely', site='http://www.inf.ufrgs.br/~binsely')
	db.professores.insert(id=63, email='cabral@inf.ufrgs.br', short_name='Cabral', full_name='Roberto Cabral de Mello Borges')
	db.professores.insert(id=64, email='rdasilva@inf.ufrgs.br', short_name='Roberto', full_name='Roberto da Silva', site='http://www.inf.ufrgs.br/~rdasilva')
	db.professores.insert(id=65, email='cechin@inf.ufrgs.br', short_name='Cechin', full_name='Sérgio Luis Cechin', site='http://www.inf.ufrgs.br/~cechin')
	db.professores.insert(id=66, email='roesler@inf.ufrgs.br', short_name='Roesler', full_name='Valter Roesler', site='http://www.inf.ufrgs.br/~roesler')
	db.professores.insert(id=67, email='viviane@inf.ufrgs.br', short_name='Viviane', full_name='Viviane Pereira Moreira', site='http://www.inf.ufrgs.br/~viviane')
	db.professores.insert(id=68, email='juergen@inf.ufrgs.br', short_name='Juergen', full_name='Juergen Rochol', site='http://www.inf.ufrgs.br/~juergen')
	db.professores.insert(id=69, email='nina@inf.ufrgs.br', short_name='Nina', full_name='Nina Edelweiss', site='http://www.inf.ufrgs.br/~nina')
	db.professores.insert(id=70, email='tomprice@inf.ufrgs.br', short_name='Tom Price', full_name='Roberto Tom Price')
	db.professores.insert(id=71, email='amaciel@inf.ufrgs.br', short_name='Anderson Maciel', full_name='Anderson Maciel', site='http://www.inf.ufrgs.br/~amaciel')
	db.professores.insert(id=72, email='jnj@inf.ufrgs.br', short_name='José Junior', full_name='José Nicoletti Junior')
	db.professores.insert(id=73, email='karin.becker@inf.ufrgs.br', short_name='Karin Becker', full_name='Karin Becker', site='http://www.inf.ufrgs.br/~kbecker')
	db.professores.insert(id=74, email='franca@inf.ufrgs.br', short_name='França', full_name='Luis de França Gonçalves Ferreira')
	db.professores.insert(id=75, email='caco@inf.ufrgs.br', short_name='Caco', full_name='Antônio Carlos Beck Filho')
	db.professores.insert(id=76, email='ivone@inf.ufrgs.br', short_name='Ivone', full_name='Ivone Maluf Medero')
	db.professores.insert(id=77, email='ral@inf.ufrgs.br', short_name='Roque', full_name='Roque Antônio Lima')
