
if db(db.professores.id > 0).count() == 0:
	db.professores.insert(id=1, email='flavio@inf.ufrgs.br', short_name='Flávio', full_name='Flávio Rech Wagner')
	db.professores.insert(id=2, email='lamb@inf.ufrgs.br', short_name='Lamb', full_name='Luís da Cunha Lamb')
	db.professores.insert(id=3, email='heuser@inf.ufrgs.br', short_name='Heuser', full_name='Carlos Alberto Heuser')
	db.professores.insert(id=4, email='daltro@inf.ufrgs.br', short_name='Daltro', full_name='Daltro José Nunes')
	db.professores.insert(id=5, email='palazzo@inf.ufrgs.br', short_name='Palazzo', full_name='José Palazzo Moreira de Oliveira')
	db.professores.insert(id=6, email='navaux@inf.ufrgs.br', short_name='Navaux', full_name='Philippe Olivier Alexandre Navaux')
	db.professores.insert(id=7, email='reis@inf.ufrgs.br', short_name='Reis', full_name='Ricardo Augusto da Luz Reis')
	db.professores.insert(id=8, email='asc@inf.ufrgs.br', short_name='Carissimi', full_name='Alexandre da Silva Carissimi')
	db.professores.insert(id=9, email='bazzan@inf.ufrgs.br', short_name='Bazzan', full_name='Ana Lucia Cetertich Bazzan')
	db.professores.insert(id=10, email='carla@inf.ufrgs.br', short_name='Carla', full_name='Carla Maria Dal Sasso Freitas')
	db.professores.insert(id=11, email='calisboa@inf.ufrgs.br', short_name='Lisboa', full_name='Carlos Arthur Lang Lisboa')
	db.professores.insert(id=12, email='cora@inf.ufrgs.br', short_name='Cora', full_name='Cora Helena Francisconi Pinto Ribeiro')
	db.professores.insert(id=13, email='barone@inf.ufrgs.br', short_name='Barone', full_name='Dante Augusto Couto Barone')
	db.professores.insert(id=14, email='ingrid@inf.ufrgs.br', short_name='Ingrid', full_name='Ingrid Eleonora Schreiber Jansch Pôrto')
	db.professores.insert(id=15, email='jacobs@inf.ufrgs.br', short_name='Jacob', full_name='Jacob Scharcanski')
	db.professores.insert(id=16, email='netto@inf.ufrgs.br', short_name='Netto', full_name='João Cesar Netto')
	db.professores.insert(id=17, email='valdeni@inf.ufrgs.br', short_name='Valdeni', full_name='José Valdeni de Lima')
	db.professores.insert(id=18, email='leila@inf.ufrgs.br', short_name='Leila', full_name='Leila Ribeiro')
	db.professores.insert(id=19, email='carro@inf.ufrgs.br', short_name='Luigi', full_name='Luigi Carro')
	db.professores.insert(id=20, email='alvares@inf.ufrgs.br', short_name='Luis Otavio', full_name='Luis Otavio Campos Alvares')
	db.professores.insert(id=21, email='bercht@inf.ufrgs.br', short_name='Magda', full_name='Magda Bercht')
	db.professores.insert(id=22, email='souto@inf.ufrgs.br', short_name='Cida Souto', full_name='Maria Aparecida Martins Souto')
	db.professores.insert(id=23, email='blauth@inf.ufrgs.br', short_name='Blauth', full_name='Paulo Fernando Blauth Menezes')
	db.professores.insert(id=24, email='engel@inf.ufrgs.br', short_name='Engel', full_name='Paulo Martins Engel')
	db.professores.insert(id=25, email='weber@inf.ufrgs.br', short_name='Weber', full_name='Raul Fernando Weber')
	db.professores.insert(id=26, email='rpribas@inf.ufrgs.br', short_name='Ribas', full_name='Renato Perez Ribas')
	db.professores.insert(id=27, email='rosa@inf.ufrgs.br', short_name='Rosa', full_name='Rosa Maria Viccari')
	db.professores.insert(id=28, email='bampi@inf.ufrgs.br', short_name='Bampi', full_name='Sérgio Bampi')
	db.professores.insert(id=29, email='zirbes@inf.ufrgs.br', short_name='Zirbes', full_name='Sérgio Felipe Zirbes')
	db.professores.insert(id=30, email='taisy@inf.ufrgs.br', short_name='Taisy', full_name='Taisy Silva Weber')
	db.professores.insert(id=31, email='diverio@inf.ufrgs.br', short_name='Tiaraju', full_name='Tiaraju Asmuz Diverio')
	db.professores.insert(id=32, email='avillavicencio@inf.ufrgs.br', short_name='Aline', full_name='Aline Villavicencio')
	db.professores.insert(id=33, email='afmoreira@inf.ufrgs.br', short_name='Álvaro', full_name='Álvaro Freitas Moreira')
	db.professores.insert(id=34, email='andreis@inf.ufrgs.br', short_name='André', full_name='André Inácio Reis')
	db.professores.insert(id=35, email='cirano@inf.ufrgs.br', short_name='Cirano', full_name='Cirano Iochpe')
	db.professores.insert(id=36, email='geyer@inf.ufrgs.br', short_name='Geyer', full_name='Cláudio Fernando Resin Geyer')
	db.professores.insert(id=37, email='crjung@inf.ufrgs.br', short_name='Jung', full_name='Cláudio Jung')
	db.professores.insert(id=38, email='prestes@inf.ufrgs.br', short_name='Prestes', full_name='Edson Prestes e Silva Júnior')
	db.professores.insert(id=39, email='erika@inf.ufrgs.br', short_name='Érika', full_name='Érika Fernandes Cota')
	db.professores.insert(id=40, email='fglima@inf.ufrgs.br', short_name='Fernanda', full_name='Fernanda Gusmão de Lima Kastensmidt')
	db.professores.insert(id=41, email='fernando@inf.ufrgs.br', short_name='Fernando', full_name='Fernando Rosa do Nascimento')
	db.professores.insert(id=42, email='vauthier@inf.ufrgs.br', short_name='Helena', full_name='Helena Saint Pastous Vauthier de Souza')
	db.professores.insert(id=43, email='brodbeck@inf.ufrgs.br', short_name='Brodbeck', full_name='Henrique Jorge Brodbeck')
	db.professores.insert(id=44, email='comba@inf.ufrgs.br', short_name='Comba', full_name='João Luiz Dihl Comba')
	db.professores.insert(id=45, email='wives@inf.ufrgs.br', short_name='Leandro', full_name='Leandro Krug Wives')
	db.professores.insert(id=46, email='granville@inf.ufrgs.br', short_name='Lisandro', full_name='Lisandro Zambenedetti Granville')
	db.professores.insert(id=47, email='nedel@inf.ufrgs.br', short_name='Nedel', full_name='Luciana Porcher Nedel')
	db.professores.insert(id=48, email='buriol@inf.ufrgs.br', short_name='Buriol', full_name='Luciana Salete Buriol')
	db.professores.insert(id=49, email='paschoal@inf.ufrgs.br', short_name='Paschoal', full_name='Luciano Paschoal Gaspary')
	db.professores.insert(id=50, email='lmduarte@inf.ufrgs.br', short_name='Lucio', full_name='Lucio Mauro Duarte')
	db.professores.insert(id=51, email='oliveira@inf.ufrgs.br', short_name='Manuel', full_name='Manuel Menezes de Oliveira Neto')
	db.professores.insert(id=52, email='marabel@inf.ufrgs.br', short_name='Mara', full_name='Mara Abel')
	db.professores.insert(id=53, email='johann@inf.ufrgs.br', short_name='Johann', full_name='Marcelo de Oliveira Johann')
	db.professores.insert(id=54, email='mpimenta@inf.ufrgs.br', short_name='Pimenta', full_name='Marcelo Soares Pimenta')
	db.professores.insert(id=55, email='marcelo.walter@inf.ufrgs.br', short_name='Walter', full_name='Marcelo Walter')
	db.professores.insert(id=56, email='mrpritt@inf.ufrgs.br', short_name='Ritt', full_name='Marcus Rolf Peter Ritt')
	db.professores.insert(id=57, email='marinho@inf.ufrgs.br', short_name='Marinho', full_name='Marinho Pilla Barcellos')
	db.professores.insert(id=58, email='newton@inf.ufrgs.br', short_name='Newton', full_name='Newton Braga Rosa')
	db.professores.insert(id=59, email='nicolas@inf.ufrgs.br', short_name='Nicolas', full_name='Nicolas Bruno Maillard')
	db.professores.insert(id=60, email='bordini@inf.ufrgs.br', short_name='Bordini', full_name='Rafael Heitor Bordini')
	db.professores.insert(id=61, email='galante@inf.ufrgs.br', short_name='Renata', full_name='Renata de Matos Galante')
	db.professores.insert(id=62, email='binsely@inf.ufrgs.br', short_name='Bins Ely', full_name='Roberto Bins Ely')
	db.professores.insert(id=63, email='cabral@inf.ufrgs.br', short_name='Cabral', full_name='Roberto Cabral de Mello Borges')
	db.professores.insert(id=64, email='rdasilva@inf.ufrgs.br', short_name='Roberto', full_name='Roberto da Silva')
	db.professores.insert(id=65, email='cechin@inf.ufrgs.br', short_name='Cechin', full_name='Sérgio Luis Cechin')
	db.professores.insert(id=66, email='roesler@inf.ufrgs.br', short_name='Roesler', full_name='Valter Roesler')
	db.professores.insert(id=67, email='viviane@inf.ufrgs.br', short_name='Viviane', full_name='Viviane Pereira Moreira')
	db.professores.insert(id=68, email='juergen@inf.ufrgs.br', short_name='Juergen', full_name='Juergen Rochol')
	db.professores.insert(id=69, email='nina@inf.ufrgs.br', short_name='Nina', full_name='Nina Edelweiss')
	db.professores.insert(id=70, email='tomprice@inf.ufrgs.br', short_name='Tom Price', full_name='Roberto Tom Price')
